
# Kong Global Plugins
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-global
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: rate-limiting
config:
  second: {{ .Values.kongPlugins.rateLimiting.requests_per_second }}
  minute: {{ .Values.kongPlugins.rateLimiting.requests_per_minute }}
  hour: {{ .Values.kongPlugins.rateLimiting.requests_per_hour }}
  policy: local
  hide_client_headers: false
---
# Request Termination Plugin for Private Routes
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-termination-private
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: request-termination
config:
  status_code: 401
  content_type: "application/json"
  body: '{"error": "Access denied", "message": "Private endpoints are not accessible"}'
---
# CORS Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
    - X-Auth-Token
  exposed_headers:
    - X-Auth-Token
  credentials: true
  max_age: 3600
---
