
# Kong Global Plugins
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-global
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: rate-limiting
config:
  second: {{ .Values.kongPlugins.rateLimiting.requests_per_second }}
  minute: {{ .Values.kongPlugins.rateLimiting.requests_per_minute }}
  hour: {{ .Values.kongPlugins.rateLimiting.requests_per_hour }}
  policy: local
  hide_client_headers: false
---
# Request Termination Plugin for Private Routes
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-termination-private
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: request-termination
config:
  status_code: 401
  content_type: "application/json"
  body: '{"error": "Access denied", "message": "Private endpoints are not accessible"}'
---
# CORS Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
    - X-Auth-Token
  exposed_headers:
    - X-Auth-Token
  credentials: true
  max_age: 3600
---
# Custom JWT Auth Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: custom-jwt-auth
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: custom-jwt-auth
config:
  keycloak_base_url: "https://keycloak.example.com"
  keycloak_realm: "master"
  expected_issuer: "https://keycloak.example.com/realms/master"
  expected_audience: "kong-api"
  cache_ttl: 3600
  ssl_verify: false
---
# Custom Auth Pre-Function Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: custom-auth-pre-function
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: custom-auth-pre-function
config:
  auth_service_url: {{ .Values.kongPlugins.customAuthPreFunction.auth_service_url | quote }}
  auth_service_timeout: {{ .Values.kongPlugins.customAuthPreFunction.auth_service_timeout }}
  ssl_verify: {{ .Values.kongPlugins.customAuthPreFunction.ssl_verify }}
  retry_count: {{ .Values.kongPlugins.customAuthPreFunction.retry_count }}