{{/*
Dynamic Kong Ingress generation from values.yaml routes configuration
This template generates Kong Ingress resources for each route type defined in values
*/}}

{{- range $routeType, $routeConfig := .Values.routes }}
{{- if $routeConfig.enabled }}
---
# {{ $routeType | title }} Routes - {{ $routeConfig.description }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-{{ $routeType }}-routes
  annotations:
    {{- if $routeConfig.plugins }}
    konghq.com/plugins: {{ $routeConfig.plugins | join "," }}
    {{- end }}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-routes
    route-type: {{ $routeType }}
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      {{- range $pathConfig := $routeConfig.paths }}
      - path: {{ $pathConfig.path }}
        pathType: {{ $pathConfig.pathType | default "Prefix" }}
        backend:
          service:
            name: {{ $pathConfig.service }}
            port:
              number: {{ $pathConfig.port }}
      {{- end }}
{{- end }}
{{- end }}

