
# Kong Global Plugins
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-global
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: rate-limiting
config:
  second: {{ .Values.kongPlugins.rateLimiting.requests_per_second }}
  minute: {{ .Values.kongPlugins.rateLimiting.requests_per_minute }}
  hour: {{ .Values.kongPlugins.rateLimiting.requests_per_hour }}
  policy: local
  hide_client_headers: false
---
# Custom JWT Plugin with Keycloak JWKS Integration
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: custom-jwt-auth
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: pre-function
config:
  access:
    - |
      {{- if .Values.luaScripts.enabled }}
      -- External Lua script: {{ .Values.luaScripts.customJwtAuth.filename }}
      -- Configuration values are rendered by Helm templating
      local KEYCLOAK_BASE_URL = "{{ .Values.keycloak.baseUrl }}"
      local KEYCLOAK_REALM = "{{ .Values.keycloak.realm }}"
      local EXPECTED_ISSUER = "{{ .Values.keycloak.expectedIssuer }}"
      local EXPECTED_AUDIENCE = "{{ .Values.keycloak.expectedAudience }}"
      
{{ .Files.Get "lua-scripts/custom-jwt-auth.lua" | indent 6 }}
      {{- else }}
      -- Fallback: external scripts disabled
      kong.log.warn("[custom-jwt] External scripts disabled, no authentication performed")
      kong.response.exit(500, { error = "Authentication not configured" })
      {{- end }}
---
# Request Termination Plugin for Private Routes
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: request-termination-private
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: request-termination
config:
  status_code: 401
  content_type: "application/json"
  body: '{"error": "Access denied", "message": "Private endpoints are not accessible"}'
---


# External Auth Plugin using Kong's native HTTP capabilities
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: custom-auth-pre-function
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: pre-function
config:
  access:
    - |
      {{- if .Values.luaScripts.enabled }}
      -- External Lua script: {{ .Values.luaScripts.customAuthPreFunction.filename }}
      -- Configuration values are rendered by Helm templating
      local AUTH_SERVICE_URL = "{{ .Values.authService.url }}"
      local AUTH_SERVICE_TIMEOUT = {{ .Values.authService.timeout | default 10000 }}
      
{{ .Files.Get "lua-scripts/custom-auth-pre-function.lua" | indent 6 }}
      {{- else }}
      -- Fallback: external scripts disabled
      kong.log.warn("[custom-auth] External scripts disabled, no authentication performed")
      kong.response.exit(500, { error = "Authentication not configured" })
      {{- end }}

---
# CORS Plugin
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app.kubernetes.io/name: kong-gateway-poc
    app.kubernetes.io/component: kong-plugin
plugin: cors
config:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
    - X-Auth-Token
  exposed_headers:
    - X-Auth-Token
  credentials: true
  max_age: 3600